refactor(#5): remove rebuild and add it to creation and using OIDC connection
Signed-off-by: Mykyta Mozghovoi <n.mozgowoi2017@gmail.com>

diff --git a/.github/workflows/sandbox-deletion.yml b/.github/workflows/sandbox-deletion.yml
--- a/.github/workflows/sandbox-deletion.yml
+++ b/.github/workflows/sandbox-deletion.yml
@@ -10,24 +10,37 @@ on:
 env:
   AWS_REGION: ${{ vars.AWS_REGION }}
 
+permissions:
+  id-token: write
+  contents: read
+
 jobs:
   trigger-pipeline:
     runs-on: ubuntu-latest
     steps:
       - name: Validate environment variables
         run: |
-          if [ -z "${{ vars.AWS_REGION }}" ]; then
+          if [ -z "${{ env.AWS_REGION }}" ]; then
             echo "::error::AWS_REGION variable is not set"
             exit 1
           fi
 
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ secrets.AWS_CODEPIPELINE_ROLE_ARN }}
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Validate Required Secrets
+        run: |
+          if [ -z "${{ secrets.AWS_SANDBOX_DELETION_PIPELINE_NAME }}" ]; then
+            echo "::error::AWS_SANDBOX_DELETION_PIPELINE_NAME secret is not set"
+            exit 1
+          fi
 
       - name: Trigger AWS CodePipeline
-        uses: aws-actions/aws-codepipeline-action@v1
-        with:
-          pipeline-name: sandbox-deletion
-          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          region: ${{ env.AWS_REGION }}
+        run: |
+          aws codepipeline start-pipeline-execution --name "${{ secrets.AWS_SANDBOX_DELETION_PIPELINE_NAME }}"
