refactor(#82): add validation for variable
Signed-off-by: Mykyta Mozghovoi <n.mozgowoi2017@gmail.com>

diff --git a/.github/workflows/sandbox-deleting.yml b/.github/workflows/sandbox-deleting.yml
--- a/.github/workflows/sandbox-deleting.yml
+++ b/.github/workflows/sandbox-deleting.yml
@@ -24,6 +24,10 @@ jobs:
             echo "::error::AWS_REGION variable is not set"
             exit 1
           fi
+          if [ -z "${{ vars.PROD_AWS_ACCOUNT_ID }}" ]; then
+            echo "::error::PROD_AWS_ACCOUNT_ID variable is not set"
+            exit 1
+          fi
 
       - name: Checkout code
         uses: actions/checkout@v4
