refactor(#135): cahnge variable validation place

diff --git a/.github/workflows/sandbox-creating.yml b/.github/workflows/sandbox-creating.yml
--- a/.github/workflows/sandbox-creating.yml
+++ b/.github/workflows/sandbox-creating.yml
@@ -19,6 +19,13 @@ jobs:
   check-tokens:
     runs-on: ubuntu-latest
     steps:
+      - name: Validate AWS Region
+        run: |
+          if [ -z "${{ vars.AWS_REGION }}" ]; then
+            echo "::error::AWS_REGION is not set"
+            exit 1
+          fi
+
       - name: Configure AWS Credentials (Test)
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -156,13 +163,6 @@ jobs:
           role-to-assume: arn:aws:iam::${{vars.PROD_AWS_ACCOUNT_ID}}:role/sandbox-creation-trigger-role
           role-session-name: GitHub_to_AWS_via_FederatedOIDC
           aws-region: ${{ env.AWS_REGION }}
-
-      - name: Validate AWS Region
-        run: |
-          if [ -z "${{ vars.AWS_REGION }}" ]; then
-            echo "::error::AWS_REGION is not set"
-            exit 1
-          fi
 
       - name: Start Pipeline Execution
         run: |
