fix(#82): fix workflow execution
Signed-off-by: Mykyta Mozghovoi <n.mozgowoi2017@gmail.com>

diff --git a/.github/workflows/sandbox-deletion.yml b/.github/workflows/sandbox-deletion.yml
--- a/.github/workflows/sandbox-deletion.yml
+++ b/.github/workflows/sandbox-deletion.yml
@@ -17,6 +17,7 @@ env:
 permissions:
   id-token: write
   contents: read
+  pull-requests: read
 
 jobs:
   trigger-pipeline:
@@ -39,6 +40,30 @@ jobs:
           role-session-name: GitHub_to_AWS_via_FederatedOIDC
           aws-region: ${{ env.AWS_REGION }}
 
+      - name: Get PR Number
+        id: get_pr_number
+        run: |
+          PR_NUMBER=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github+json" \
+            "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?head=${GITHUB_REPOSITORY_OWNER}:${GITHUB_REF_NAME}" | jq -r '.[0].number')
+          echo "PR_NUMBER=$PR_NUMBER"
+          if [ -z "$PR_NUMBER" ]; then
+            echo "PR_NUMBER not found for branch ${BRANCH_NAME}"
+            exit 1
+          fi
+          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
+        env:
+          GITHUB_TOKEN: ${{ secrets.PAT_WITH_REPO_PERMISSIONS }}
+
       - name: Trigger AWS CodePipeline
         run: |
-          aws codepipeline start-pipeline-execution --name "sandbox-deletion" --variables '{"name": "BRANCH_NAME", "value": "${BRANCH_NAME}"}'
+          PR_NUMBER="${{ env.PR_NUMBER }}"
+          if ! aws codepipeline start-pipeline-execution \
+            --name "sandbox-deletion" \
+            --variables \
+              "name=BRANCH_NAME,value=${BRANCH_NAME}" \
+              "name=PR_NUMBER,value=${PR_NUMBER}" \
+              "name=IS_PULL_REQUEST,value=0"; then
+            echo "::error::Failed to start pipeline execution"
+            exit 1
+          fi
